config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", :sessions => "users/sessions" }
  
  devise_scope :user do
    get '/auth/facebook/callback', to: 'callbacks#facebook'
  end
  
  root 'posts#index'
  
  # get    '/login',   to: 'sessions#new'
  # post   '/login',   to: 'sessions#create'
  # get '/logout',  to: 'sessions#destroy'
  # get 'auth/facebook', as: "auth_provider"
  
  
  resources :posts do
    member do
      post 'add', to: 'posts#add'
      post 'remove', to: 'posts#remove'
    end
  end
  
  resources :users
  
  resources :updates, only: [:new, :create]
end

app/models/post.rb
class Post < ActiveRecord::Base
  require 'carrierwave/orm/activerecord'
  
  validates :title, presence: true
  validates :description, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :picture, presence: true
  validates :contact_number, numericality: { only_integer: true }, allow_blank: true
  validates_presence_of :tag
  
  mount_uploader :picture, PictureUploader
  
  belongs_to :user
  has_many :signups
  has_many :updates
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index]

  # GET /posts
  # GET /posts.json
  def index
    Post.all.each do |p|
      if p.end_time < Date.today
        p.destroy
      end
    end
    
    if params[:tag] == "All" || params[:tag].nil?
      @posts = Post.all.order(created_at: :desc)
    else
      @posts = Post.where(tag: params[:tag]).order(created_at: :desc)
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @url = "https://orbital-soraares.c9users.io/posts/#{@post.id}"
    @uploader = PictureUploader.new
    if current_user.oauth_token
      @friends = []
      if current_user.friendslist.length > 0
        current_user.friendslist.each do |friend|
          user = User.find_by(uid: friend["id"])
          if Signup.find_by(user_id: user.id, post_id: @post.id)
            @friends << friend
          end
        end  
      end
    end
  end

  # GET /posts/new
  def new
    if !user_signed_in?
      respond_to do |format|
        format.html { redirect_to root_url, notice: 'Login to add a post!' }
        format.json { head :no_content }
      end
    end
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    if !user_signed_in?
      respond_to do |format|
        format.html { redirect_to root_url, notice: 'Login to add a post!' }
        format.json { head :no_content }
      end
    end
      
    @post = Post.new(post_params)
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render @post, status: :created, location: :show }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def add
    if !user_signed_in?
      respond_to do |format|
        format.html { redirect_to root_url, notice: 'Login to add to calendar!' }
      end
    end
    
    signup = Signup.find_by(user_id: current_user.id, post_id: set_post.id)
    
    if signup != nil
      respond_to do |format|
        format.html { redirect_to set_post and return}
        flash[:notice] = 'Event already in calendar!'
      end
    end
    
    @signup = Signup.new(user_id: current_user.id, post_id: set_post.id)
    @signup.save
    respond_to do |format|
      format.html { redirect_to @post }
      flash[:success] = 'Added to calendar!'
    end
  end
  
  
  def remove
    @signup = Signup.find_by(user_id: current_user.id, post_id: params[:id])
    if @signup.destroy
      respond_to do |format|
        format.html { redirect_to current_user, notice: 'Event was removed from calendar' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :host, :start_time, :end_time, :picture, :user_id, :contact_number, :signup_link, :tag)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<head>
  <title>Create Post</title>
</head>

<body>

<%= semantic_form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="padding-bottom:10px;">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>

  </div>
  
  <div class="field" style="padding-bottom:10px;">
    <%= f.label :host %><br>
    <%= f.text_area :host, class: "form-control" %>
  </div>
  
  <div class="field" style="padding-bottom:10px;">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  
  <div class="field" style="padding-bottom:10px;">
    <%= f.label :signup_link %><br>
    <%= f.text_area :signup_link, class: "form-control" %>
  </div>
  
  <div class="field" style="padding-bottom:10px;">
    <%= f.label :contact_number %><br>
    <%= f.text_area :contact_number, class: "form-control" %>
  </div>
  
  <div class="field" style="padding-bottom:10px;">
    
    <%= f.label "Start Date" %><br>
    <%= f.input :start_time, input_html: { class: "daterange" }, as: :string, class:"starttimetable", label: false %>
    <script type="text/javascript">
    $(document).ready(function() {
      $('input[class="daterange"]').daterangepicker({
        locale: {
          format: 'YYYY-MM-DD'
        },
        "singleDatePicker": true,
        "showDropdowns": true
        }, 
        
        function(start, end, label) {
          console.log("New date range selected: ' + start.format('YYYY/MM/DD h:mm A') + ' to ' + end.format('YYYY/MM/DD h:mm A') + ' (predefined range: ' + label + ')");
        });
    });
    </script>
    
  </div>
  
  <div class="field" style="padding-bottom:10px;">
    
    <%= f.label :"End Date" %> &nbsp;
    <%= f.input :end_time, input_html: { class: "daterange" }, as: :string, label: false %>
    <script type="text/javascript">
    $(document).ready(function() {
      $('input[class="daterange"]').daterangepicker({
        locale: {
          format: 'YYYY-MM-DD'
        },
        "singleDatePicker": true,
        "showDropdowns": true
        }, 
        
        function(start, end, label) {
          console.log("New date range selected: ' + start.format('YYYY/MM/DD') + ' to ' + end.format('YYYY/MM/DD') + ' (predefined range: ' + label + ')");
        });
    });
    </script>
  </div>
  
  <div class="field" style="padding-bottom:10px;">
    <%= f.label :tag %><br>
    <%= f.select :tag, options_for_select(["Sports", "Arts", "Community", "Education", "Tech"]), { class: "select", :id => "soflow" } %>
  </div>
  
  <div class="field" style="padding-bottom:10px;">
    <%= f.label :picture %><br>
    <%= f.file_field :picture, id: :post_picture, class: "form-control" %>
  </div>
  
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  
  <br>
  
  <div class="actions" style="text-align:center;">
    <%= f.submit class:"darkbluebutton"%>
  </div>
  
<% end %>
</body>

app/views/posts/edit.html.erb
<head>
  <%= stylesheet_link_tag    'posts', media: 'all', 'data-turbolinks-track' => true %>
</head>

<div class="col-sm-2"></div>
<div class="col-sm-8">
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= stylesheet_link_tag    'posts', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag    'slick', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag    'slick-theme', media: 'all', 'data-turbolinks-track' => true %>

<body>
  <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
  <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <!--<script type="text/javascript" src="slick/slick.min.js"></script>-->
  
  <p id="notice"><%= notice %></p>
  <div class="col-sm-1"></div>
  <div class="col-sm-10">
  <h1>Posts</h1>
  <%= form_tag posts_path, method: :get %>
    <%= select_tag :tag, options_for_select(["All", "Sports", "Arts", "Community", "Education", "Tech"]), { class: "styled-select slate" } %>
  <%= submit_tag "Filter", class: "greybutton" %>
  
  <%= javascript_include_tag 'slick.min' %>
  <%= javascript_include_tag 'slick' %>
  
  <script type="text/javascript">
    $(document).ready(function(){
      $('.scroller').slick({
        // nextArrow: '<i class="glyphicon glyphicon-chevron-right"></i>',
        // prevArrow: '<i class="glyphicon glyphicon-chevron-left"></i>',
        centerMode: true,
        centerPadding: '60px',
        slidesToShow: 2,
        responsive: [
          {
            breakpoint: 768,
            settings: {
              arrows: false,
              centerMode: true,
              centerPadding: '40px',
              slidesToShow: 1
            }
          },
          {
            breakpoint: 480,
            settings: {
              arrows: true,
              centerMode: true,
              centerPadding: '40px',
              slidesToShow: 1
            }
          }
        ]
      });
    });
  </script>
  
  <div class="scroller" style='padding-bottom: 5%;'>
    <% @posts.each do |post| %>
    <div>
      <br>
      <%= image_tag post.picture_url.to_s, class:"img-thumbnail" %>
      <div class="caption" style="background: rgba(255, 255, 255, 0.7);">
        <div style="text-align:center; font-size:1.5em; opacity:0.7; background-color: #F5F5F5;">
        <a href= '<%= post.signup_link %>'>Signup</a> &nbsp; or &nbsp; 
        <%= link_to "View More", post, method: :get %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  
  <div style="text-align:center;">
  <%= image_tag "polaroid.png", size: "200" %>
  </div>
  
</body>

app/views/posts/new.html.erb
<%= stylesheet_link_tag    'posts', media: 'all', 'data-turbolinks-track' => true %>


<div class="col-sm-2"></div>
<div class="col-sm-8" style="padding-bottom: 5%; padding-top: 2%;">
<h1>New Post</h1>
<%= render 'form' %>
<div style="text-align:center">
<%= link_to 'Back', posts_path, class:"btn btn-link" %>
</div>
</div>

app/views/posts/show.html.erb
<%= stylesheet_link_tag    'posts', media: 'all', 'data-turbolinks-track' => true %>

<body>
  <div class="col-sm-7" style="padding-left: 40px; text-align: center;">
      <%= image_tag @post.picture_url.to_s  %>
      <br>
      <% if user_signed_in? && @post.user_id == current_user.id %>
      <br>
        <%= button_to "Edit Post!", edit_post_path, class:"btn btn-info", method: :get %> &nbsp;
        <%= button_to "Create an Update", new_update_path(@post), class:"btn btn-success", method: :get %>
      <% end %>
      <br>
      <!--<div class="fb-comments" data-href="https://orbital-soraares.c9users.io/posts" data-width="700" data-numposts="5" style="background:white;" data-href="https://orbital-soraares.c9users.io/posts/27"></div>-->
      <div class="fb-comments" data-href=<%= @url %> data-numposts="5" style="background:white;"></div>
      <br><br>
      <%= social_share_button_tag(@post.title, :allow_sites => %w(twitter facebook google_plus tumblr pinterest email linkedin wechat reddit hacker_news telegram)) %>
      <br>
    </div>
  </div>
  </div>
  
  <div class="col-sm-4">
    <strong style="font-size:3.5em; font-family: 'Anton', sans-serif; "><%= @post.title %></strong>
    
    <p style="font-weight: 300;">
      by <%= @post.host %>
    </p>
    
    <p>
      <span class="label label-info"><%= @post.tag %></span>
    </p>
    
    <p>
    <strong> Date</strong>
    <br>
    <%= @post.start_time.strftime("%d %B %Y") %>  
    <% if !@post.start_time.eql? @post.end_time %>
    &nbsp; to  &nbsp; <%= @post.end_time.strftime("%d %B %Y") %>
    <% end %>
    </p>
    
    <p>
      <% if user_signed_in? %>
        <%= button_to "Add to Calendar!", add_post_path, class:"btn btn-primary btn-sm" %>
        <br>
      <% end %>
    </p>
    
    <p>
    <strong> Description</strong>
    <br>
    <%= @post.description %>
    <br>
    <% if @post.contact_number.length > 0 %>
        <div>Have any questions? For more details contact us @ <%= @post.contact_number %>!</div>
      <% end %>
    </p>
    
    <p style="font-weight: bold; font-size: 2em; text-align: center;">
      <a href= '<%= @post.signup_link %>'>Signup Here!</a><br>
    </p>
    
    <p>
      <% if @friends && @friends.length > 0 %>
      <strong>Friends going for the event</strong>
        <% @friends.take(3).each do |friend| %>
          <p><%= friend["name"] %></p>
          <p><%= image_tag friend["picture"]["data"]["url"] %></p>
        <% end %>
      <% end %>
    </p>
    
  </div>   
</body>

<!--<div class="col-sm-3">-->
<!--  <table>-->
<!--    <thead>-->
<!--      <tr>-->
<!--        <th>Event Title</th>-->
<!--        <th colspan="3"></th>-->
<!--      </tr>-->
<!--    </thead>-->
  
<!--    <tbody>-->
<!--      <%# @posts.each do |po| %>-->
<!--        <tr>-->
<!--          <td><%#= po.title %></td>-->
<!--          <td><%#= link_to 'Show', po, class:"btn btn-primary" %></td>-->
<!--          <td><%#= link_to 'Delete', remove_post_path(po.id), method: :post, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>-->
<!--        </tr>-->
<!--      <%# end %>-->
<!--    </tbody>-->
<!--  </table>-->
<!--</div>-->